// Services/requestCookies.js
//
// 2026-Q3 — Per-request cookie support for the yt-dlp path.
//
// The Flutter client captures the user's OWN session cookies from its
// in-app browser (HttpOnly-aware, via CookieJar.liveCookieHeaderForUrl /
// getAllStored) and sends them in the /api/download body:
//
//   { url, cookies: { youtube: "LOGIN_INFO=...; SID=...",
//                     twitter: "auth_token=...; ct0=...",
//                     instagram: "sessionid=...", facebook: "xs=..." } }
//
// The IG/FB scrapers already read cookies.instagram / cookies.facebook and
// pass them as header strings to their HTTP calls. yt-dlp, however, only
// accepts cookies as a Netscape-format `cookies.txt` file (`--cookies`).
// This module converts a `k=v; k=v` header string into such a file in a
// per-request temp path so YouTube age-gate / bot-wall, NSFW/protected
// tweets, and any of the ~1700 generic sites can be fetched with the
// user's real session — WITHOUT the operator having to bake a shared
// account into YT_DLP_COOKIES_FILE.
//
// Security / hygiene:
//   • Files are written to os.tmpdir() with a random name, 0600 perms.
//   • Callers MUST call cleanup(path) in a finally block. A boot-time and
//     hourly sweep also removes any stragglers older than 1h.
//   • Cookie VALUES are never logged — only counts.

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const crypto = require('crypto');

const TMP_PREFIX = 'wa-cookies-';
const MAX_AGE_MS = 60 * 60 * 1000; // 1h straggler sweep

// Map a platform/domain key to the cookie DOMAIN written into the file.
// yt-dlp matches cookies by domain, so a too-narrow host (e.g. "x.com")
// would miss "api.x.com". We use a leading-dot wildcard domain so the
// cookie applies to every subdomain.
const DOMAIN_FOR_PLATFORM = {
  youtube:   '.youtube.com',
  twitter:   '.x.com',
  x:         '.x.com',
  instagram: '.instagram.com',
  facebook:  '.facebook.com',
  tiktok:    '.tiktok.com',
  reddit:    '.reddit.com',
  vimeo:     '.vimeo.com',
};

/**
 * Infer the cookie domain for a platform key or a raw URL.
 * @param {string} platformOrUrl
 * @returns {string} a leading-dot domain, or '' if it can't be inferred
 */
function inferDomain(platformOrUrl) {
  const key = String(platformOrUrl || '').toLowerCase();
  if (DOMAIN_FOR_PLATFORM[key]) return DOMAIN_FOR_PLATFORM[key];
  // Treat it as a URL/host.
  try {
    const host = key.includes('://')
      ? new URL(key).hostname
      : key.replace(/^\.+/, '').split('/')[0];
    if (!host || !host.includes('.')) return '';
    const parts = host.split('.');
    // Registrable-ish domain: last two labels, prefixed with a dot.
    return '.' + parts.slice(-2).join('.');
  } catch (_) {
    return '';
  }
}

/**
 * Write a Netscape cookies.txt file from a `k=v; k=v` header string.
 *
 * @param {string} cookieHeader   e.g. "LOGIN_INFO=abc; SID=xyz"
 * @param {string} platformOrUrl  platform key ('youtube') or the target URL
 * @returns {string|null} absolute temp-file path, or null when there is
 *          nothing usable to write (empty header / no domain).
 */
function writeCookieFile(cookieHeader, platformOrUrl) {
  const header = String(cookieHeader || '').trim();
  if (!header) return null;
  const domain = inferDomain(platformOrUrl);
  if (!domain) return null;

  const pairs = [];
  for (const part of header.split(';')) {
    const idx = part.indexOf('=');
    if (idx <= 0) continue;
    const name  = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (!name) continue;
    pairs.push([name, value]);
  }
  if (!pairs.length) return null;

  // Netscape cookies.txt format. Columns are TAB-separated:
  //   domain  includeSubdomains  path  secure  expiry  name  value
  // includeSubdomains TRUE because we wrote a leading-dot domain.
  // expiry: 0 → session-ish; yt-dlp accepts it. We set a far-future
  // stamp so yt-dlp never treats them as already-expired.
  const expiry = 2147483647; // 2038; safely "not expired"
  const lines = ['# Netscape HTTP Cookie File', '# Generated by WebAura requestCookies'];
  for (const [name, value] of pairs) {
    lines.push([domain, 'TRUE', '/', 'TRUE', String(expiry), name, value].join('\t'));
  }

  const file = path.join(
    os.tmpdir(),
    `${TMP_PREFIX}${crypto.randomBytes(9).toString('hex')}.txt`,
  );
  try {
    fs.writeFileSync(file, lines.join('\n') + '\n', { mode: 0o600 });
    console.log(`🍪 requestCookies: wrote ${pairs.length} cookie(s) for ${domain} → temp file`);
    return file;
  } catch (e) {
    console.warn(`🍪 requestCookies: write failed — ${e.message}`);
    return null;
  }
}

/** Best-effort delete of a temp cookie file. Safe to call with null. */
function cleanup(file) {
  if (!file) return;
  try { fs.unlinkSync(file); } catch (_) {}
}

/**
 * Pull the right cookie header for [platform] out of a request-body
 * `cookies` object, tolerating a few key aliases (twitter/x).
 * @returns {string} header string, or '' if none supplied
 */
function headerFor(cookies, platform) {
  if (!cookies || typeof cookies !== 'object') return '';
  const key = String(platform || '').toLowerCase();
  const direct = cookies[key];
  if (typeof direct === 'string' && direct.trim()) return direct.trim();
  if (key === 'twitter' && typeof cookies.x === 'string') return cookies.x.trim();
  if (key === 'x' && typeof cookies.twitter === 'string') return cookies.twitter.trim();
  return '';
}

// Remove stragglers older than MAX_AGE_MS (crash-safety net — normal
// flow deletes in a finally block).
function sweep() {
  try {
    const dir = os.tmpdir();
    const now = Date.now();
    for (const name of fs.readdirSync(dir)) {
      if (!name.startsWith(TMP_PREFIX)) continue;
      const full = path.join(dir, name);
      try {
        if (now - fs.statSync(full).mtimeMs > MAX_AGE_MS) fs.unlinkSync(full);
      } catch (_) {}
    }
  } catch (_) {}
}
sweep();
setInterval(sweep, MAX_AGE_MS).unref();

module.exports = { writeCookieFile, cleanup, headerFor, inferDomain };
